name       : libidl
version    : 0.8.14
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libIDL/0.8/libIDL-0.8.14.tar.bz2 : c5d24d8c096546353fbc7cedf208392d5a02afe9d56ebcc1cccb258d7c4d2220
license    : LGPL-2.0-or-later
component  : programming.library
summary    : libIDL is a library for creating trees of CORBA Interface Definition Language (IDL) files
description: |
    libIDL is a library licensed under the GNU LGPL for creating trees of CORBA Interface Definition Language (IDL) files, which is a specification for defining portable interfaces.  libIDL was initially written for ORBit (the ORB from the GNOME project, and the primary means of libIDL distribution).  However, the functionality was designed to be as reusable and portable as possible.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
